import { StatusCodes } from "http-status-codes";
import { randomBytes } from "crypto";
import { anonymousSessionRepository } from "../../repositories/anonymous-session.repository";
import { referralRepository } from "../../repositories/referral.repository";
import { memberMetricsRepository } from "../../repositories/member-metrics.repository";
import { urlRepository } from "../../repositories/url.repository";

type ServiceError = Error & { statusCode?: number };

const buildServiceError = (message: string, statusCode: number): ServiceError => {
  const error = new Error(message) as ServiceError;
  error.statusCode = statusCode;
  return error;
};

export class AnonSessionService {
  /**
   * Create an anonymous session, optionally tied to a member referrer
   */
  async createSession(input: {
    userAgent: string;
    ipHash: string;
    referralCode?: string;
  }): Promise<{ sessionId: string; sessionToken: string; memberId?: string }> {
    let memberId: string | undefined;

    // If referral code provided, look up the member
    if (input.referralCode) {
      const referral = await referralRepository.findByCode(input.referralCode);
      if (!referral) {
        throw buildServiceError("Invalid referral code", StatusCodes.BAD_REQUEST);
      }
      memberId = String(referral.ownerId);
    }

    // Generate unique session token
    const sessionToken = randomBytes(32).toString("hex");

    // Create the session
    const session = await anonymousSessionRepository.createSession({
      sessionToken,
      userAgent: input.userAgent,
      ipHash: input.ipHash,
      referralCode: input.referralCode,
      memberId
    });

    if (!session) {
      throw buildServiceError(
        "Unable to create anonymous session",
        StatusCodes.INTERNAL_SERVER_ERROR
      );
    }

    // Track this user as brought by the member
    if (memberId) {
      await memberMetricsRepository.getOrCreateMetrics(memberId);
      await memberMetricsRepository.incrementUsersBrought(memberId, 1);
    }

    return {
      sessionId: String(session.id),
      sessionToken,
      memberId
    };
  }

  /**
   * Validate and retrieve an existing session
   */
  async getSession(sessionToken: string): Promise<{
    sessionToken: string;
    memberId?: string;
    referralCode?: string;
  } | null> {
    const session = await anonymousSessionRepository.findByToken(sessionToken);
    if (!session) return null;

    return {
      sessionToken: session.sessionToken,
      memberId: session.memberId ? String(session.memberId) : undefined,
      referralCode: session.referralCode ?? undefined
    };
  }

  /**
   * Get member's anonymous user statistics
   */
  async getMemberStats(
    memberId: string
  ): Promise<{
    totalUsersBrought: number;
    totalLinksGenerated: number;
    totalQualifiedClicks: number;
    totalEarnings: number;
    thisMonthUsers: number;
    thisMonthEarnings: number;
  } | null> {
    const metrics = await memberMetricsRepository.findByMemberId(memberId);
    if (!metrics) return null;

    return {
      totalUsersBrought: metrics.totalAnonymousUsersBrought,
      totalLinksGenerated: metrics.totalAnonymousLinksGenerated,
      totalQualifiedClicks: metrics.totalQualifiedClicks,
      totalEarnings: metrics.totalEarnings,
      thisMonthUsers: metrics.thisMonthUsers,
      thisMonthEarnings: metrics.thisMonthEarnings
    };
  }

  /**
   * Get detailed traffic sessions for a member
   */
  async getMemberTrafficSessions(
    memberId: string,
    query: { page: number; limit: number }
  ): Promise<{
    items: Array<{
      sessionId: string;
      createdAt: Date;
      linksGenerated: number;
      totalClicks: number;
      earnings: number;
    }>;
    pagination: { page: number; limit: number; total: number; totalPages: number };
  }> {
    const { data, total } = await anonymousSessionRepository.findByMemberId(memberId, query);

    const items = await Promise.all(
      data.map(async (session) => {
        // Aggregate stats for this session
        // Find all URLs generated by this session
        const urls = await urlRepository.findByAnonymousSessionId(session.id);
        
        const linksGenerated = urls.length;
        const totalClicks = urls.reduce((sum, url) => sum + (url.clickCount || 0), 0);
        
        // In a real system, earnings would be tracked per session or per URL.
        // For now, we estimate based on qualified completions if possible, 
        // but here we'll just return the link count and total clicks.
        // We'll mock earnings as (clicks * rate) for display purposes if not explicitly stored.
        const earnings = totalClicks * 0.5; // Mock rate

        return {
          sessionId: String(session.id).substring(0, 8) + "...", // Masked ID
          createdAt: session.createdAt,
          linksGenerated,
          totalClicks,
          earnings
        };
      })
    );

    return {
      items,
      pagination: {
        page: query.page,
        limit: query.limit,
        total,
        totalPages: Math.max(1, Math.ceil(total / query.limit))
      }
    };
  }

  /**
   * Track that an anonymous user generated a link
   */
  async trackLinkGeneration(memberId?: string): Promise<void> {
    if (memberId) {
      await memberMetricsRepository.incrementLinksGenerated(memberId, 1);
    }
  }
}

export const anonSessionService = new AnonSessionService();
