"use client";

import { useEffect, useState } from "react";
import { useAuthStore } from "@/store/auth.store";
import { apiRequest } from "@/lib/api-client";
import Link from "next/link";
import { AdminAppShell } from "@/components/admin/admin-app-shell";

type AnonLink = {
  shortCode: string;
  shortUrl: string;
  originalUrl: string;
  createdAt: string;
  totalClicks: number;
  qualifiedClicks: number;
};

export default function AnonLinksPage() {
  const token = useAuthStore((state) => state.accessToken);
  const user = useAuthStore((state) => state.user);
  const [links, setLinks] = useState<AnonLink[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchLinks = async () => {
      if (!token || !user?.id) {
        setError("Not authenticated");
        setLoading(false);
        return;
      }

      try {
        // This endpoint would need to be created in the backend
        const data = await apiRequest<AnonLink[]>(
          `/users/${user.id}/anonymous-links`,
          { method: "GET", token }
        );
        setLinks(data || []);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load links");
      } finally {
        setLoading(false);
      }
    };

    fetchLinks();
  }, [token, user?.id]);

  if (loading) {
    return (
      <AdminAppShell>
        <div className="flex items-center justify-center min-h-screen bg-slate-50">
          <div className="animate-spin rounded-full border-4 border-indigo-600 border-t-transparent h-8 w-8"></div>
        </div>
      </AdminAppShell>
    );
  }

  return (
    <AdminAppShell>
      <div className="min-h-screen bg-slate-50 text-slate-700">
        <div className="mx-auto max-w-4xl px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <Link href="/dashboard/partner/referral-link" className="text-blue-600 hover:text-blue-600 mb-4 inline-block">
            ← Back to Referral Code
          </Link>
          <h1 className="text-3xl font-bold text-white mb-2">Anonymous Links</h1>
          <p className="text-slate-600">Links generated by users who joined through your referral</p>
        </div>

        {error && (
          <div className="rounded-lg border border-rose-700 bg-rose-950/30 p-4 mb-8">
            <p className="text-rose-300">{error}</p>
          </div>
        )}

        {links.length === 0 ? (
          <div className="rounded-2xl border border-slate-200 bg-white p-8 text-center">
            <p className="text-slate-500">No anonymous links yet.</p>
            <p className="mt-2 text-sm text-slate-500">
              Links will appear here when users join through your referral code.
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            {links.map((link) => (
              <div key={link.shortCode} className="rounded-lg border border-slate-200 bg-white p-6">
                <div className="flex items-start justify-between mb-4">
                  <div className="flex-1">
                    <p className="text-sm text-slate-500 mb-1">Short URL</p>
                    <p className="font-mono text-blue-600 truncate">{link.shortUrl}</p>
                  </div>
                  <button
                    onClick={() => navigator.clipboard.writeText(link.shortUrl)}
                    className="ml-4 rounded bg-blue-600 px-3 py-1 text-sm font-semibold text-white hover:bg-blue-500"
                  >
                    Copy
                  </button>
                </div>

                <p className="text-sm text-slate-500 mb-1">Original URL</p>
                <p className="text-sm text-slate-600 truncate mb-4">{link.originalUrl}</p>

                <div className="grid grid-cols-3 gap-4">
                  <div>
                    <p className="text-xs text-slate-500">Total Clicks</p>
                    <p className="text-lg font-semibold text-white">{link.totalClicks}</p>
                  </div>
                  <div>
                    <p className="text-xs text-slate-500">Qualified Clicks</p>
                    <p className="text-lg font-semibold text-emerald-400">{link.qualifiedClicks}</p>
                  </div>
                  <div>
                    <p className="text-xs text-slate-500">Created</p>
                    <p className="text-sm text-slate-600">{new Date(link.createdAt).toLocaleDateString()}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  </AdminAppShell>
  );
}
